### ISSUE TITLE
OpenAPI Generator currently not working

### ISSUE THREAD

**Issue by devops-monkeys** [eclipse/vorto#1973] opened 2019-09-25 12:12 UTC
Since a couple of days the OpenAPI generator is not working anymore. When trying to download an OpenAPI spec via Vorto Website, I get a

`Whitelabel Error Page`
`This application has no explicit mapping for /error, so you are seeing this as a fallback.`
`Wed Sep 25 12:05:36 UTC 2019`
`There was an unexpected error (type=Internal Server Error, status=500).`
`Cannot create repository session for user`

Via Postman I get a 
`406 - Not Acceptable`

**Comment by aedelmann** [comment] 2019-09-25 13:23
Hi @devops-monkeys 
which model are you trying to generate for ? 
I cannot reproduce this. I was trying to generate openAPI  for https://vorto.eclipse.org/#/details/com.bosch.iot.suite.example.octopussuiteedition:OctopusSuiteEdition:1.0.0 and it is working fine.

**Comment by somesh-kumar** [comment] 2019-09-26 02:57
Hey @devops-monkeys can you share the model link?

**Comment by devops-monkeys** [comment] 2019-09-26 07:31
Hi @aedelmann, hi @somesh-kumar,
These are some of the models - 
SmartHomeController:1.0.0 
MotionDetector:1.0.0 
ShutterControl:1.0.0

Here's the link that's configured in our jobs - 
https://vorto.eclipse.org/api/v1/plugins/generators/openapi/models/com.bosch.sh:SmartHomeController:1.0.0?digitaltwin=boschiotthings

**Comment by somesh-kumar** [comment] 2019-09-26 10:42
@devops-monkeys , tried it out with your link and was able to generate the openapi yml. Since your models are in draft state and not public you must provide the github bearer token in the authorization header. Generate it from your GitHub account seetings>developer settings> personal access token> leave everything unchecked

**Comment by philbuettner** [comment] 2019-09-26 10:43
We provide the bearer token.

**Comment by philbuettner** [comment] 2019-09-26 10:45
Via Web-Interface it is working now. Maybe there was a conflict with another model version? All I changed to was to delete another version of one of the models.

**Comment by somesh-kumar** [comment] 2019-09-27 03:31
@philbuettner , if you face the issue again do raise a ticket with steps to reproduce the issue. Closing the bug for now.

**Closed** 2019-09-27 03:40 UTC
Labels: question
