### ISSUE TITLE
Cannot save models when created in a subdomain if user is not sysadmin

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2349] opened 2020-03-18 14:24 UTC
Either the Save button is not visible, or if it is, saving returns 404 and 403 for the generated requests

**Comment by mena-bosch** [comment] 2020-03-18 15:06
Suspect I know the root cause, albeit unable to replicate. Working with issuer internally and will likely PR a fix today.

**Comment by mena-bosch** [comment] 2020-03-19 07:17
Fine-tune as of yesterday: one thing that was not specified initially (which is why I think none of us could replicate) is that the problem occurs only with sub-namespaces, e.g. in the model creation wizard, type a name for a child of the target namespace before creating the model. 
This does replicate at least one significant aspect of the issue, i.e. no "Save" button.
Working on.

**Comment by mena-bosch** [comment] 2020-03-19 10:07
Bug replicates with sysadmins when replicating with the correct conditions - adapting title appropriately.

**Comment by mena-bosch** [comment] 2020-03-23 14:31
Fix successfully applied and deployed, but it was hiding a bigger issue for some users only (i.e. not replicable my side) --> it seems the loss of ACLs on models after reimport is preventing some users from saving models they have access to. 
Will formalize in a new ticket and close this one.

**Closed by mena-bosch** 2020-03-23 14:31 UTC
Labels: bug
