### ISSUE TITLE
Resolution of datatype models in functionblockmodel DSL not working properly

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#88] opened 2016-03-14 06:33 UTC
Migrated from https://bugs.eclipse.org/bugs/show_bug.cgi?id=474013

**Comment by erlemantos** [comment] 2016-03-21 09:00
This looks like an issue in resolving qualified names .. I'll take a look at this.

**Comment by Ebolon** [comment] 2017-11-18 18:50
Seems like the DSL has changed since 2015. Can not reproduce the Bug. For me it seems ok.

```
namespace de.fzi.sensidl
version 1.0.0
entity EnergyTransfer
{
	mandatory energyPhase1 as float
	mandatory energyPhase2 as float
	mandatory energyPhase3 as float
}
```

```
namespace de.fzi.sensidl
version 1.0.0
displayname "eMeter"
description "Function block model for eMeter"
category powermeter
using de.fzi.sensidl.EnergyTransfer ; 1.0.0

functionblock EMeter {
	configuration {
	}

	status {
	}

	fault {
	}

	operations {
		getPhase1() returns EnergyTransfer "transmission frequency for phase measurements provides measurements for phase 1"
	}
}
```

(PhaseTransfer description was missing. Replaced it with EnergyTransfer)

**Closed** 2018-05-07 02:50 UTC
Labels: Eclipse Toolset Editor, bug
