### ISSUE TITLE
Default constraint does not work for float and boolean

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2491] opened 2020-07-14 12:11 UTC
```
status {
        abc as boolean <DEFAULT true>
}
```
Leads to error: 
Line 10 - This constraint value must be of a Short

**Comment by mena-bosch** [comment] 2020-10-14 14:39
Could not replicate for float. A DEFAULT constraint of either an integer or a dot-notation floating value works. 
@kolotu am I missing something crucial?

Does replicate with boolean, no boolean or actually no short value works there.

**Comment by mena-bosch** [comment] 2020-10-14 14:46
Also, boolean constraint issue replicates within a datatype declaration (not surprisingly since the constraint is defined in the datatype resource and used in the fb one).

**Comment by kolotu** [comment] 2020-10-15 06:48
@mena-bosch it does replicate for floats (and doubles) that end with .0 - i.e. 1.0
Seems like I only tested with .0 values before...

**Comment by mena-bosch** [comment] 2020-10-15 08:08
> @mena-bosch it does replicate for floats (and doubles) that end with .0 - i.e. 1.0
> Seems like I only tested with .0 values before...

It gets weirder. 

- `foo as float <DEFAULT 0.0>` --> ok
- `foo as float <DEFAULT 0.1>` --> ok
- `foo as float <DEFAULT 1.0>` --> `no viable alternative at input '1.0'`  ¯\_(ツ)_/¯
- `foo as float <DEFAULT 2.0>` --> ok again...

Also worth noting the parsing error messages are different in case of boolean vs float. 

- `boo as boolean <DEFAULT true>` --> `This constraint value must be of a Short `

Probably different issues in the grammar.

**Comment by mena-bosch** [comment] 2020-10-15 11:58
New and probably useless finding: the generated validation Java source does compare boolean representations with their values **enclosed in double-quotes**, so that never seems to work within context. 
It also sends the wrong error message (for the short type) when invalid, which "explains" the absurd validation error for the boolean constraint, but doesn't really add much to clarity.

**Comment by mena-bosch** [comment] 2020-10-15 12:10
> New and probably useless finding: the generated validation Java source does compare boolean representations with their values **enclosed in double-quotes**, so that never seems to work within context.
> It also sends the wrong error message (for the short type) when invalid, which "explains" the absurd validation error for the boolean constraint, but doesn't really add much to clarity.

Which leads me to the `AccordinglyValueValidator.xtend` resource. 
Can assume the "Long type" error message is a typo. 
Trying to loosen the comparison to at least add non-quoted "false" and "true" when evaluating boolean values.

**Comment by mena-bosch** [comment] 2020-10-15 12:43
Fixing the xtend resource seems to work. I think the invocation of `equalsIgnoreCase` had some issues on its own, so I just added all possible values (including the ones enclosed in double quotes that were previously there) in a collection, and am verifying whether the value parsed is contained. 
The issue with some float values is likely on a different level - I don't necessarily expect the validation to be the cause of the problem but will take a look next.

**Comment by mena-bosch** [comment] 2020-10-15 13:42
Confirmed the float part of this issue should not be impacted by the validation itsel as the `1.0` value is parsed as `null` when it reaches it. 
Also weird but out of scope that signed int only accepts "-".

**Comment by mena-bosch** [comment] 2020-10-16 12:07
Now I have confirmed that the inability to parse `1.0` in a constraint comes from the enum representing the VortoLangVersion. 
If I change the version to e.g. `1.1`, then a constraint with value `1.0` will successfully parse the float as non-null, whereas conversely, a `1.1` constraint value will parse as null, and therefore fail to validate when `Float.parseFloat` is invoked. 

With my limited knowledge of xtext I suspect the enum constant somehow "conflicts" with the FLOAT rule when that value is involved.

No idea how to fix that yet.

**Comment by mena-bosch** [comment] 2020-10-16 14:41
I was able to address the lexer issue by removing the VortoLangVersion enum and turning the vortolang version declaration into a single literal `vortolang 1.0` in the xtext resources. 
This has required re-mapping the weird xtend formatters that derived the rules from the generated grammars.
At this point, it's only a POC solution. 
Next step would be to at least re-introduce a "variable" vortolang version # by e.g. trying to turn the old enum into a simple rule, so far containing only `1.0` as literal. 
This should make the solution more robust, e.g. to add `2.0` etc. to supported versions. 

Will require some thorough review.

**Comment by mena-bosch** [comment] 2020-10-19 09:21
As discussed, I am going to be forking this task to #2652 for the easy fix on boolean validation, while the `1.0` value float lexing issue will remained scoped here, as it will take much longer to resolve.

**Comment by mena-bosch** [comment] 2020-10-26 13:57
Closing this and #2490 since it's merged.

**Closed by mena-bosch** 2020-10-26 13:57 UTC
Labels: bug
