### ISSUE TITLE
Cannot generate model because no access to self_owned models

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1867] opened 2019-07-29 04:03 UTC
After logging in to my account which was used to create all of the models, I can't use the official plugins anymore since it says: "You need access to the complete model..." even though I created all the models with the logged in account.

![image](https://user-images.githubusercontent.com/16529337/62021148-65d56380-b1f8-11e9-8b6d-61b0ab85b4fa.png)

Somehow one of the referenced models from the same namespace shows me no access.

I tried:
- Logging out and in again 
- Reloading the page
- Reloading the page of the `ID` model

**Comment by aedelmann** [comment] 2019-07-29 08:37
@timgrossmann 
The root problem is something else which impacts the possibility to not generate code anymore. Models can only be generated if all models can be accessed by the user. Since you are the owner of all these models, you should be able to generate. 
I can see in your list of references, that the ID model is referenced twice with the same name, namespace and version. This is rather strange why this ID shows up twice and would need be further analyzed.

**Comment by aedelmann** [comment] 2019-07-29 08:41
@erlemantos 
You have an idea, why this issue would occur ?

**Comment by erlemantos** [comment] 2019-07-29 10:42
No idea. I can check out the logs.

**Comment by aedelmann** [comment] 2019-08-13 14:33
Cannot reproduce this problem with latest patch release in prod. Closing this issue for now, but lets keep an eye on this.

**Closed by aedelmann** 2019-08-13 14:33 UTC
Labels: bug
