### ISSUE TITLE
Vorto perspective appears twice in Open perspective window

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#272] opened 2016-06-16 02:49 UTC
**Steps taken**
Uninstalled the previous version and installed new version of Vorto.
Clicked Open perspective from the menu
**Expected result**
Only one Vorto perspective is available
**Actual result**
Vorto perspective appears twice

**Comment by gavinying** [comment] 2016-06-27 06:33
more information: 
If I do upgrading to latest nightly build, it seems no such issue. 
However, the old perspective tab may still be there if it has been opened previously, just close it and open the new perspective from eclipse menu.

**Comment by erlemantos** [comment] 2016-07-22 03:58
I can't reproduce this issue. I didn't even uninstall the old one. As long as you close the old perspective, I don't think there's an issue.

**Comment by deepagithub** [comment] 2016-08-04 03:19
Steps to reproduce this issue:

First, install Vorto from the update site http://download.eclipse.org/vorto/update/milestones/ 

Uninstall this version

Download another version from http://download.eclipse.org/vorto/update/nightly-snapshots/

Check the perspective.

**Comment by aedelmann** [comment] 2016-08-15 09:44
Add remark/hint in documentation to close existing Vorto perspective before Upgrading toolset.

**Closed** 2016-08-15 23:47 UTC
Labels: bug, Documentation, in progress, Stability
