### ISSUE TITLE
OpenAPI Generator - entities are generating duplicated mapping keys

### ISSUE THREAD

**Issue by philbuettner** [eclipse/vorto#2172] opened 2019-12-11 16:30 UTC
When generating OpenAPI documents, in some documents the following error appears:
Parser error - duplicated mapping key

This error only appears in connection with an entity object inside of a .type model. Because the OpenAPI Generator Template function, which parses entities did not changed from current release (0.12.4) to development branch, the cause of that error must be somewhere else (in 0.12.4 this error does not appear).

This function:
https://github.com/eclipse/vorto/blob/2657685397bcf9a0f361843d8508fffcead3eef2/generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/templates/OpenAPITemplate.xtend#L615

generates this error in the development branch:
```
    Incident:
      type: object
      properties:
        incidentType:
          $ref: '#/components/schemas/IncidentType'
        roomId:
          type: string
        timeOfIncident:
          $ref: '#/components/schemas/DateTime'
~~~ Parser error - duplicated mapping key
        incidentType:
          $ref: '#/components/schemas/IncidentType'
        roomId:
          type: string
        timeOfIncident:
          $ref: '#/components/schemas/DateTime'
```

The following OpenAPI documents are containing the duplicated keys. If you compare them with each other, there are also slightly different in the block order. Documents which are generated correctly, always have the same order. But I am not sure if this was by coincident.

[OpenAPIgeneratedWithDuplicatedKeys.zip](https://github.com/eclipse/vorto/files/3951189/OpenAPIgeneratedWithDuplicatedKeys.zip)

**Comment by t-gauss** [comment] 2020-01-10 09:37
I'll look into it.

**Comment by mschoeffler** [comment] 2020-01-17 08:44
Not sure if still required, but maybe it helps to find the actual problem: @bboersig and I came also across this bug. The problem is that "entity.properties"...
https://github.com/eclipse/vorto/blob/2657685397bcf9a0f361843d8508fffcead3eef2/generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/templates/OpenAPITemplate.xtend#L615
... has the doubled amount of properties as expected. 

When digging deeper, we saw that org.eclipse.vorto.plugin.utils.Utils.getReferencedEntities... https://github.com/eclipse/vorto/blob/2657685397bcf9a0f361843d8508fffcead3eef2/generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/Utils.xtend#L45
...returns indeed duplicates. 

As far as I remember, the only difference between these duplicates is that the presence field is set only for one duplicate and the constraint rule field only for the other one.

As we were doing only some prototyping, we applied a hotfix by simply filtering the properties collection (generator code level) --> "entities.properties.filter[presence !== null]". 
Btw. we took the idea of this hotfix from here: 
https://github.com/eclipse/vorto/blob/2657685397bcf9a0f361843d8508fffcead3eef2/generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/Utils.xtend#L72

**Comment by t-gauss** [comment] 2020-01-17 14:48
Thanks for the hint and thanks @philbuettner  for providing the models. I need to ask a beginner question since I'm new to the topic: I tried to reproduce this but the only way I was able to was by creating an entity with two properties having the same ID. Is this the problem which is described here? In the example information models I cannot see this.

**Comment by philbuettner** [comment] 2020-01-17 14:51
I don't know why, but I can't reproduce this behaviour anymore with the official current Vorto release.

**Comment by philbuettner** [comment] 2020-01-17 14:52
> 
> 
> Thanks for the hint and thanks @philbuettner for providing the models. I need to ask a beginner question since I'm new to the topic: I tried to reproduce this but the only way I was able to was by creating an entity with two properties having the same ID. Is this the problem which is described here? In the example information models I cannot see this.

This error occured with a unique property id.

**Comment by t-gauss** [comment] 2020-01-17 15:03
Hello @mschoeffler ,
could you let me know in which scenario you encounter this problem? Does it happen with unique property IDs as well?

**Comment by mschoeffler** [comment] 2020-01-20 10:47
Hi, the bug occurs with any model configuration, including unique properties. I just tried it out with a very basic infomodel --> [vorto.private.mschoeffler.temp_Test_1.0.0.zip](https://github.com/eclipse/vorto/files/4085298/vorto.private.mschoeffler.temp_Test_1.0.0.zip)

In order to reproduce the bug, I go to information model and start the Open API Generator from there. The generated file has a duplicate of 'temperature':

```
    TestEntity:
      type: object
      properties:
        temperature:
          type: number
        temperature:
          type: number
      required: [temperature]
```

I did my test on the current code basis --> 19.01.20, commit 86de67af514efac149c4d1e5202a8b3cb7e124e4

My guess is that the bug occurs while parsing/importing the Vorto model. I did only a very brief debugging: getFlatStatusProperties seems to add a duplicate to the entity (line 212). Not something that I would have expected from a "get method". 

https://github.com/eclipse/vorto/blob/f065ac8f833e2c3a9789a784816277e11de95807/core-bundles/meta-model/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/ModelConversionUtils.java#L212

**Comment by t-gauss** [comment] 2020-01-20 15:12
Hello @mschoeffler ,
many thanks for the example model. When I do this in my local dev environment I don't see this issue. I will look into it.

**Comment by t-gauss** [comment] 2020-01-20 15:52
Hello @mschoeffler ,
I tried this in the production environment. Even there it is working. It seems to be a problem with the generator runner.

**Comment by t-gauss** [comment] 2020-01-27 15:20
[PR here](https://github.com/eclipse/vorto/pull/2259)
Seems as if this was introduced in October 2019. I changed it as suggested by @mschoeffler  - thanks for the hint.

**Comment by t-gauss** [comment] 2020-01-27 15:43
Needed to close the PR because my fix removes the pattern if available. I need to re-check.

**Closed** 2020-01-29 08:42 UTC
Labels: Code Generators, bug
