### ISSUE TITLE
Can't change image of my vorto model

### ISSUE THREAD

**Issue by Ineskouka** [eclipse/vorto#2305] opened 2020-02-20 13:05 UTC

**Comment by mena-bosch** [comment] 2020-02-26 10:27
Looking at. 
So far I have replicated the main issue, which also seems to have a workaround:

1. Delete the previous picture in the attachments section
2. Save
3. Upload another picture by clicking on the picture's viewport ("click to change image")
4. The model reloads with the right picture - save, optionally

My suspicion is that it always picks the first attachment as picture, maybe filtered by MIME type.

**Comment by mena-bosch** [comment] 2020-02-26 12:43
Strongly suspect root cause is in this line:

`Optional<FileContent> imageContent = modelRepo.getAttachmentContent(modelID, imageAttachments.get(0).getFilename());`

... in `ModelRepositoryController`. 

A suitable workaround might be simply to sort and ensure LIFO.

**Comment by mena-bosch** [comment] 2020-02-26 13:24
> A suitable workaround might be simply to sort and ensure LIFO.

Looks like easier said than done in this context.

**Comment by kolotu** [comment] 2020-02-26 13:48
@mena-bosch or introduce a dedicated tag for the display image.

**Comment by mena-bosch** [comment] 2020-02-26 13:48
> > A suitable workaround might be simply to sort and ensure LIFO.
> 
> Looks like easier said than done in this context.

Attachment nodes have not been set as versionable, so there is no real sorting criteria save for persisting additional data for each attachment (which seems arguably a bit overkill here). 

I think I could add a specific tag for the image selected (e.g. "display_image"), so that Vorto would know to add it when uploading an image, and remove it from all other image attachments within the transaction. 

Conversely this might improve the rendering of the image a bit, as the back-end would only filter by this specific tag, which only one attachment would have (instead of fetching all images and just returning the first one). 

Before going, there I'll check if the nodes returned by modeshape aren't _somehow_ sorted chronologically - in that case it might be much easier to just fetch the last item of the list.

**Comment by mena-bosch** [comment] 2020-02-26 13:49
> @mena-bosch or introduce a dedicated tag for the display image.

lol see below

**Comment by kolotu** [comment] 2020-02-26 13:50
> > @mena-bosch or introduce a dedicated tag for the display image.
> 
> lol see below

damn I was too fast ;)

**Comment by mena-bosch** [comment] 2020-02-26 14:38
> > > @mena-bosch or introduce a dedicated tag for the display image.
> > 
> > 
> > lol see below
> 
> damn I was too fast ;)

The more I think of it, the better the new tag looks. The alternative was to try and rely on whether modeshape somehow sorts the nodes chronologically but even if that worked, I wouldn't trust the deep implementations in modeshape to not change.

In a perfect world, you'd have some UI to select which of the image-compatible attachments should be the IM's image, but I think this is a bit too much here, at least until someone actually wants that.

**Comment by kolotu** [comment] 2020-02-26 14:43
I think a UI would be to much at the current state, since you can upload a picture and then automatically add the new tag to it and remove the tag from any other attachments, if there are any with that tag. 
What do you think?

**Comment by mena-bosch** [comment] 2020-02-26 14:47
> I think a UI would be to much at the current state, since you can upload a picture and then automatically add the new tag to it and remove the tag from any other attachments, if there are any with that tag.
> What do you think?

Yes, precisely.

**Comment by mena-bosch** [comment] 2020-02-27 11:30
PR merged

**Closed by mena-bosch** 2020-02-27 11:30 UTC
Labels: bug
