### ISSUE TITLE
Vorto Dashboard stopped working

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2565] opened 2020-08-26 07:01 UTC
Could be related to the SuiteAuth switch from Keycloak to Hydra. Verify that the correct v2 endpoints for Hydra are used by the Dashboard.

When starting the Vorto Dashboard, the authentication fails with this message: 

Backend queried with filterString... 
JWT expired, getting new Token Mon Aug 10 2020 10:11:27 GMT+0200 (CEST)... StatusCodeError: 401 - {"status":401,"error":"gateway:authentication.failed","message":"Multiple authentication mechanisms were applicable but none succeeded.","description":"For a successful authentication see the following suggestions: { The JSON Web Token is not valid. }, { Please provide a valid JWT in the authorization header prefixed with 'Bearer ' }."}
Simulator not running Error: Command failed: kill -0 $(ps aux | grep -E '[p]ython PMSMotorSimulator.py|TraciTagSimulator.py' | grep -v grep | awk '{print $2}')
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

**Comment by mena-bosch** [comment] 2020-08-27 13:49
Currently investigating with the folks at SuiteAuth. 

The main difference between obtaining a token through the app and doing so manually on https://accounts.bosch-iot-suite.com/oauth2-clients/show?id=someId is that both return a token, but the one obtained through the app lacks any scope and fails to authorize with the Things API (which logs that error message). 

I am not entirely sure whether the lack of scopes in the token obtained through the app is the root cause of this, but it might very well be considering it's the only difference I've seen. 

My wild guess would be some API change that hasn't been followed through by fixing the app, or maybe a recent bug on SuiteAuth's side.

**Comment by mena-bosch** [comment] 2020-09-01 13:15
After discussing with the Suite Auth Bosch team, here is a summary of what happened. 

- The Suite Auth team recently transitioned from Keycloack to Hydra for their authentication technology
- The relevant bit here is that previously, the scopes passed to the token request were ignored
- The Vorto Dashboard app had been passing the wrong key for the scope parameter all along, when requesting a token, but it was ignored
- Now that this parameter is relevant, the incorrect notation was not failing to produce a token, but obtained one that was not suitable to authorize with Things, because it did not contain the appropriate scope
- In turn, fixing this key produces a token that successfully authorizes with Things

**Comment by mena-bosch** [comment] 2020-09-01 13:32
NB: will close this when it's merged to the master branch, which implies a merge to the dev branch first.

**Comment by mena-bosch** [comment] 2020-09-03 11:20
This is now merged to the master branch.

**Closed by mena-bosch** 2020-09-03 11:20 UTC
Labels: bug
