### ISSUE TITLE
Messages after saving a model are not always displayed

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2448] opened 2020-06-11 10:35 UTC
On the current development branch, the success or error messages are not always displayed, when a model is saved. 
The success message seems to be completely missing, while the error message seems to be displayed only in some cases (my suspicion is it's only shown for syntax errors, but not for semantic errors like self-referencing an entity)

**Comment by mena-bosch** [comment] 2020-06-17 11:57
Fix is being merged to dev - keeping open for a while in case I haven't managed to fix all the scenarios found. 
The regression itself seems to be due to the fact that syntax changes around $http calls do not only impact the handlers' signatures, but also the callback payload. 
Therefore, in places where the newer signatures were already in use, no code was changed but the callback payload was not correctly referenced anymore.

**Closed** 2020-06-18 11:50 UTC
Labels: UX, bug
